name = "uuu"
license = "GPL"
licenselink = "https://www.gnu.org/licenses/gpl-3.0.txt"
description = "A Hugo theme"
homepage = "xycos.eu.org"
demosite = "xycos.eu.org"
tags = ["blog", "plain"]
features = ["blog"]
min_version = "0.01"

[author]
name = "uuu"
homepage = "https://github.com/uuxyz"
